/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import static perpustakaan.petugas.table;

/**
 *
 * @author suryani lestari 14
 */
public class anggota extends javax.swing.JInternalFrame {

    /**
     * Creates new form anggota
     */
    public anggota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        cmbkelas = new javax.swing.JComboBox<>();
        txtnis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbtrpl = new javax.swing.JRadioButton();
        rbttkj = new javax.swing.JRadioButton();
        rbttei = new javax.swing.JRadioButton();
        rbttp = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cmbka = new javax.swing.JComboBox<>();
        txtnama = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        rbtnama = new javax.swing.JRadioButton();
        rbtkelas = new javax.swing.JRadioButton();

        setBorder(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Menu_15px_1.png"))); // NOI18N
        jLabel1.setText("Data Siswa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Conference_20px_8.png"))); // NOI18N
        jLabel2.setText("Data Siswa");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("SMK TIP Cimahi");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        table.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        table.setForeground(new java.awt.Color(0, 102, 102));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIS", "Nama", "Kelas", "Jurusan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));

        cmbkelas.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbkelas.setForeground(new java.awt.Color(0, 102, 102));
        cmbkelas.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cmbkelasPopupMenuWillBecomeVisible(evt);
            }
        });
        cmbkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkelasActionPerformed(evt);
            }
        });

        txtnis.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtnis.setForeground(new java.awt.Color(0, 102, 102));
        txtnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnisActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add User Group Woman Man_20px_1.png"))); // NOI18N
        jLabel5.setText("Tambah Data Siswa");

        rbtrpl.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(rbtrpl);
        rbtrpl.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rbtrpl.setForeground(new java.awt.Color(0, 102, 102));
        rbtrpl.setSelected(true);
        rbtrpl.setText("RPL");
        rbtrpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtrplActionPerformed(evt);
            }
        });

        rbttkj.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(rbttkj);
        rbttkj.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rbttkj.setForeground(new java.awt.Color(0, 102, 102));
        rbttkj.setText("TKJ");

        rbttei.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(rbttei);
        rbttei.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rbttei.setForeground(new java.awt.Color(0, 102, 102));
        rbttei.setText("TEI");

        rbttp.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(rbttp);
        rbttp.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rbttp.setForeground(new java.awt.Color(0, 102, 102));
        rbttp.setText("TP");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("NIS");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Nama");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Kelas");

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit File_15px.png"))); // NOI18N
        jButton1.setText("Ubah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save_15px.png"))); // NOI18N
        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete_15px.png"))); // NOI18N
        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Jurusan");

        cmbka.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbka.setForeground(new java.awt.Color(0, 102, 102));
        cmbka.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cmbkaPopupMenuWillBecomeVisible(evt);
            }
        });

        txtnama.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtnama.setForeground(new java.awt.Color(0, 102, 102));
        txtnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnamaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(173, 173, 173)
                                        .addComponent(rbttkj))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtnis, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(cmbkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmbka, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtnama)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(rbtrpl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rbttei)
                                                .addGap(37, 37, 37)
                                                .addComponent(rbttp)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jButton3)))))
                .addGap(39, 39, 39))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cmbka, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rbtrpl)
                    .addComponent(rbttkj)
                    .addComponent(rbttei)
                    .addComponent(rbttp))
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Student Female_100px.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Student Male_100px_1.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search_20px.png"))); // NOI18N
        jLabel4.setText("Cari");

        txtcari.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtcari.setForeground(new java.awt.Color(0, 102, 102));
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        rbtnama.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup2.add(rbtnama);
        rbtnama.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rbtnama.setForeground(new java.awt.Color(0, 102, 102));
        rbtnama.setSelected(true);
        rbtnama.setText("Nama");

        rbtkelas.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup2.add(rbtkelas);
        rbtkelas.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rbtkelas.setForeground(new java.awt.Color(0, 102, 102));
        rbtkelas.setText("NIS");
        rbtkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtkelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(193, 193, 193))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(228, 228, 228)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(0, 144, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtnama)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtkelas))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(200, 200, 200)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(30, 30, 30))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnama)
                            .addComponent(rbtkelas)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void rbtkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtkelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtkelasActionPerformed

    private void cmbkelasPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbkelasPopupMenuWillBecomeVisible
        cmbkelas.removeAllItems();
        cmbkelas.addItem("10");
        cmbkelas.addItem("11");
        cmbkelas.addItem("12");

    }//GEN-LAST:event_cmbkelasPopupMenuWillBecomeVisible

    private void txtnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnisActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            int jawab = JOptionPane.showOptionDialog(this, "Ingin Dihapus?", "DELETE"
                    + "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if (jawab == JOptionPane.YES_OPTION) {
                koneksi.bahasasql = "DELETE FROM anggota WHERE nis='" + txtnis.getText() + "'";
                koneksi.crud();
                txtnis.setText("");
                txtnama.setText("");
                rbtrpl.setSelected(true);
                cmbkelas.removeAllItems();
                cmbka.removeAllItems();
                td.tampildataanggota(table);
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");

            } else {
            }
        } catch (SQLException ex) {
            Logger.getLogger(anggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String nis, nama, kelas, jurusan, status, apa;
            int carik, carika, caristatus;
            nis = txtnis.getText();
            nama = txtnama.getText();
            carik = cmbkelas.getSelectedIndex();
            carika = cmbka.getSelectedIndex();
            if (carik == 0) {
                kelas = "10";
            } else if (carik == 1) {
                kelas = "11";
            } else {
                kelas = "12";
            }

            if (rbtrpl.isSelected()) {
                jurusan = "RPL";
            } else if (rbttkj.isSelected()) {
                jurusan = "TKJ";
            } else if (rbttei.isSelected()) {
                jurusan = "TEI";
            } else {

                jurusan = "TP";

            }

            if (carika == 0) {
                apa = "A";
            } else if (carika == 1) {
                apa = "B";
            } else if (carika == 2) {
                apa = "C";
            } else {
                apa = "D";
            }
            if (nis.equals("") || nama.equals("")) {
                JOptionPane.showMessageDialog(this, "Lengkapi Kembali Data Anda");
            } else {
                koneksi.bahasasql = "INSERT INTO anggota VALUES ('" + nis + "','" + nama + " ','" + kelas + " " + apa + "','" + jurusan + "')";
                koneksi.crud();
                txtnis.setText("");
                txtnama.setText("");
                rbtrpl.setSelected(true);
                cmbkelas.removeAllItems();
                cmbka.removeAllItems();
                td.tampildataanggota(table);
                JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
            }

        } catch (SQLException ex) {
            Logger.getLogger(anggota.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Gagal " + ex.getMessage());
        }
        try {
            koneksi.koneksiku();
            JasperDesign JD = JRXmlLoader.load("src\\laporan\\kartuanggota.jrxml");
            JRDesignQuery JDQ = new JRDesignQuery();
            JDQ.setText("SELECT * FROM anggota WHERE NIS = '"+ txtnis.getText()+"'");
            JD.setQuery(JDQ);
                JasperReport JR = JasperCompileManager.compileReport(JD);
                JasperPrint JP = JasperFillManager.fillReport(JR, null, koneksi.koneksi);
                JasperViewer JV = new JasperViewer(JP, false);
            JV.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(anggota.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(anggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rbtrplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtrplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtrplActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String nis, nama, kelas, jurusan, status, apa;
            int carik, carika, caristatus;
            nis = txtnis.getText();
            nama = txtnama.getText();
            carik = cmbkelas.getSelectedIndex();
            carika = cmbka.getSelectedIndex();
            if (carika == 0) {
                apa = "A";
            } else if (carika == 1) {
                apa = "B";
            } else if (carika == 2) {
                apa = "C";
            } else {
                apa = "D";
            }

            if (carik == 0) {
                kelas = "10";
            } else if (carik == 1) {
                kelas = "11";
            } else {
                kelas = "12";
            }

            if (rbtrpl.isSelected()) {
                jurusan = "RPL";
            } else if (rbttkj.isSelected()) {
                jurusan = "TKJ";
            } else if (rbttei.isSelected()) {
                jurusan = "TEI";
            } else {

                jurusan = "TP";

            }
            if (nis.equals("") || nama.equals("")) {
                JOptionPane.showMessageDialog(this, "Lengkapi Kembali Data Anda");
            } else {
                koneksi.bahasasql = "UPDATE anggota SET nama_siswa='" + nama + "',kelas='" + kelas + " " + apa + " ',jurusan='" + jurusan + "' WHERE nis='" + nis + "'";
                koneksi.crud();
                txtnis.setText("");
                txtnama.setText("");
                rbtrpl.setSelected(true);
                cmbkelas.removeAllItems();
                cmbka.removeAllItems();
                td.tampildataanggota(table);
                JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");
            }

        } catch (SQLException ex) {
            Logger.getLogger(anggota.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Gagal " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        try {
            String pilihdata = table.getValueAt(table.getSelectedRow(), 0).toString();
            koneksi.bahasasql = "Select * FROM anggota WHERE nis='" + pilihdata + "'";
            koneksi.ambildata();
            txtnis.setText("");
            txtnama.setText("");
            rbtrpl.setSelected(true);
            cmbkelas.removeAllItems();
            cmbka.removeAllItems();
            while (koneksi.hasilset.next()) {
                txtnis.setText(koneksi.hasilset.getString("nis"));
                txtnama.setText(koneksi.hasilset.getString("nama_siswa"));
                if (koneksi.hasilset.getString("jurusan").equals("RPL")) {
                    rbtrpl.setSelected(true);
                    rbttkj.setSelected(false);
                    rbttei.setSelected(false);
                    rbttp.setSelected(false);
                } else if (koneksi.hasilset.getString("jurusan").equals("TKJ")) {
                    rbtrpl.setSelected(false);
                    rbttkj.setSelected(true);
                    rbttei.setSelected(false);
                    rbttp.setSelected(false);
                } else if (koneksi.hasilset.getString("jurusan").equals("TEI")) {
                    rbtrpl.setSelected(false);
                    rbttkj.setSelected(false);
                    rbttei.setSelected(true);
                    rbttp.setSelected(false);
                } else {
                    rbtrpl.setSelected(false);
                    rbttkj.setSelected(false);
                    rbttei.setSelected(false);
                    rbttp.setSelected(true);

                }
                String no, type;
                if (koneksi.hasilset.getString("kelas").equals("12 A")) {
                    cmbka.getModel().setSelectedItem("A");
                    cmbkelas.getModel().setSelectedItem("12");
                } else if (koneksi.hasilset.getString("kelas").equals("12 B")) {
                    cmbka.getModel().setSelectedItem("B");
                    cmbkelas.getModel().setSelectedItem("12");
                } else if (koneksi.hasilset.getString("kelas").equals("12 C")) {
                    cmbka.getModel().setSelectedItem("C");
                    cmbkelas.getModel().setSelectedItem("12");
                } else if (koneksi.hasilset.getString("kelas").equals("12 D")) {
                    cmbka.getModel().setSelectedItem("D");
                    cmbkelas.getModel().setSelectedItem("12");

                } else if (koneksi.hasilset.getString("kelas").equals("11 A")) {
                    cmbka.getModel().setSelectedItem("A");
                    cmbkelas.getModel().setSelectedItem("11");
                } else if (koneksi.hasilset.getString("kelas").equals("11 B")) {
                    cmbka.getModel().setSelectedItem("B");
                    cmbkelas.getModel().setSelectedItem("11");
                } else if (koneksi.hasilset.getString("kelas").equals("11 C")) {
                    cmbka.getModel().setSelectedItem("C");
                    cmbkelas.getModel().setSelectedItem("11");
                } else if (koneksi.hasilset.getString("kelas").equals("11 D")) {
                    cmbka.getModel().setSelectedItem("D");
                    cmbkelas.getModel().setSelectedItem("11");
                } else if (koneksi.hasilset.getString("kelas").equals("10 A")) {
                    cmbka.getModel().setSelectedItem("A");
                    cmbkelas.getModel().setSelectedItem("10");
                } else if (koneksi.hasilset.getString("kelas").equals("10 B")) {
                    cmbka.getModel().setSelectedItem("B");
                    cmbkelas.getModel().setSelectedItem("10");
                } else if (koneksi.hasilset.getString("kelas").equals("10 C")) {
                    cmbka.getModel().setSelectedItem("C");
                    cmbkelas.getModel().setSelectedItem("10");
                } else {
                    cmbka.getModel().setSelectedItem("D");
                    cmbkelas.getModel().setSelectedItem("10");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(anggota.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Gagal " + ex.getMessage());
        }
    }//GEN-LAST:event_tableMouseClicked

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        try {
            DefaultTableModel tm = (DefaultTableModel) table.getModel();
            tm.setRowCount(0);
            if (rbtnama.isSelected()) {
                koneksi.bahasasql = "SELECT * FROM anggota WHERE nama_siswa LIKE'%" + txtcari.getText() + "%'";
            } else {
                koneksi.bahasasql = "SELECT * FROM anggota WHERE nis LIKE'%" + txtcari.getText() + "%'";
            }

            koneksi.ambildata();
            while (koneksi.hasilset.next()) {
                String nis = koneksi.hasilset.getString("nis");
                String nama = koneksi.hasilset.getString("nama_siswa");
                String kelas = koneksi.hasilset.getString("kelas");
                String jurusan = koneksi.hasilset.getString("jurusan");
                tm.addRow(new Object[]{nis, nama, kelas, jurusan});
            }
        } catch (SQLException ex) {
            Logger.getLogger(anggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtcariKeyReleased

    private void cmbkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkelasActionPerformed

    private void cmbkaPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbkaPopupMenuWillBecomeVisible
        cmbka.removeAllItems();
        cmbka.addItem("A");
        cmbka.addItem("B");
        cmbka.addItem("C");
        cmbka.addItem("D");
    }//GEN-LAST:event_cmbkaPopupMenuWillBecomeVisible
    public void filterhuruf(KeyEvent a) {
        if (Character.isDigit(a.getKeyChar())) {
            a.consume();
            JOptionPane.showMessageDialog(this, "Masukan Hanya Huruf", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
    private void txtnamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamaKeyTyped
        filterhuruf(evt);
    }//GEN-LAST:event_txtnamaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cmbka;
    private javax.swing.JComboBox<String> cmbkelas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbtkelas;
    private javax.swing.JRadioButton rbtnama;
    private javax.swing.JRadioButton rbtrpl;
    private javax.swing.JRadioButton rbttei;
    private javax.swing.JRadioButton rbttkj;
    private javax.swing.JRadioButton rbttp;
    public static javax.swing.JTable table;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnis;
    // End of variables declaration//GEN-END:variables
}
