/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author suryani lestari 14
 */
public class buku extends javax.swing.JDialog {

    /**
     * Creates new form buku
     */
    public buku(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        paneljudul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblclose = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablebuku = new javax.swing.JTable();
        txtcaribuku = new javax.swing.JTextField();
        cmbbuku = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        paneljudul.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Menu_15px_1.png"))); // NOI18N
        jLabel1.setText("Data Buku");

        lblclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close Window_20px_6.png"))); // NOI18N
        lblclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneljudulLayout = new javax.swing.GroupLayout(paneljudul);
        paneljudul.setLayout(paneljudulLayout);
        paneljudulLayout.setHorizontalGroup(
            paneljudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneljudulLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblclose))
        );
        paneljudulLayout.setVerticalGroup(
            paneljudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneljudulLayout.createSequentialGroup()
                .addGroup(paneljudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneljudulLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))
                    .addComponent(lblclose))
                .addContainerGap())
        );

        tablebuku.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tablebuku.setForeground(new java.awt.Color(0, 102, 102));
        tablebuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Buku", "Judul Buku", "Jumlah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablebuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablebukuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablebuku);

        txtcaribuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcaribukuKeyReleased(evt);
            }
        });

        cmbbuku.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbbuku.setForeground(new java.awt.Color(0, 102, 102));
        cmbbuku.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cmbbukuPopupMenuWillBecomeVisible(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Cari Berdasarkan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneljudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcaribuku, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(paneljudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcaribuku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public static void tampildatabuku(JTable tableym) {

    
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy");
            DefaultTableModel tm = (DefaultTableModel) tableym.getModel();
            tm.setRowCount(0);
            koneksi.bahasasql = "SELECT * FROM buku";
            koneksi.ambildata();
            while (koneksi.hasilset.next()) {
                String id, judul, pengarang, penerbit, jenis;
                int tahun, jumlah;

                id = koneksi.hasilset.getString("id_buku");
                judul = koneksi.hasilset.getString("judul");
                pengarang = koneksi.hasilset.getString("pengarang");
                penerbit = koneksi.hasilset.getString("penerbit");
                tahun = koneksi.hasilset.getInt("tahun");
                jumlah = koneksi.hasilset.getInt("jumlah");
                jenis = koneksi.hasilset.getString("jenis");
                tm.addRow(new Object[]{id, judul,jumlah});
            }
        } catch (SQLException ex) {
            Logger.getLogger(buku.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }

    private void lblcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcloseMouseClicked

        this.dispose();

    }//GEN-LAST:event_lblcloseMouseClicked

    private void tablebukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablebukuMouseClicked
        
      
        try {
            String pilihid = tablebuku.getValueAt(tablebuku.getSelectedRow(), 0).toString();
            koneksi.bahasasql = "SELECT * FROM buku  WHERE id_buku = '" + pilihid + "'";
            koneksi.ambildata();
            while (koneksi.hasilset.next()) {
                String id, judul, pengarang, penerbit, jenis;
                int tahun, jumlah;
                id = koneksi.hasilset.getString("id_buku");
                judul = koneksi.hasilset.getString("judul");
                kf.pinjam.txtidbuku.setText(id);
                kf.pinjam.txtjudul.setText(judul);
            }
        } catch (SQLException ex) {
            Logger.getLogger(buku.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tablebukuMouseClicked

    private void txtcaribukuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaribukuKeyReleased
        try {
            DefaultTableModel tm = (DefaultTableModel) tablebuku.getModel();
            tm.setRowCount(0);
            int cariindex = cmbbuku.getSelectedIndex();
            if (cariindex == 0) {
                koneksi.bahasasql = "SELECT * FROM buku WHERE id_buku LIKE '%" + txtcaribuku.getText() + "%'";
            } else if (cariindex == 1) {
                koneksi.bahasasql = "SELECT * FROM buku WHERE judul LIKE '%" + txtcaribuku.getText() + "%'";
            } else {
                koneksi.bahasasql = "SELECT * FROM buku WHERE jumlah LIKE '%" + txtcaribuku.getText() + "%'";
            }

            koneksi.ambildata();
            while (koneksi.hasilset.next()) {
                String id, judul, pengarang, penerbit, jenis, tahun, jumlah;

                id = koneksi.hasilset.getString("id_buku");
                judul = koneksi.hasilset.getString("judul");
                jumlah = koneksi.hasilset.getString("jumlah");
                tm.addRow(new Object[]{id, judul, jumlah});
            }
        } catch (SQLException ex) {
            Logger.getLogger(peminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtcaribukuKeyReleased

    private void cmbbukuPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbbukuPopupMenuWillBecomeVisible
        cmbbuku.removeAllItems();
        cmbbuku.addItem("ID Buku");
        cmbbuku.addItem("Judul");
        cmbbuku.addItem("Jumlah");
    }//GEN-LAST:event_cmbbukuPopupMenuWillBecomeVisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                buku dialog = new buku(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbbuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblclose;
    private javax.swing.JPanel paneljudul;
    public static javax.swing.JTable tablebuku;
    private javax.swing.JTextField txtcaribuku;
    // End of variables declaration//GEN-END:variables
}
