/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.awt.Color;
import javax.swing.JOptionPane;
import laporan.lappetugas;


/**
 *
 * @author suryani lestari 14
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneljudul = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lblclose = new javax.swing.JLabel();
        lblmaxim = new javax.swing.JLabel();
        lblminim = new javax.swing.JLabel();
        labelkod = new javax.swing.JLabel();
        panelmenu = new javax.swing.JPanel();
        labeluser = new javax.swing.JLabel();
        labelhak = new javax.swing.JLabel();
        panelkonten = new javax.swing.JPanel();
        panelside = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        labelbuku = new javax.swing.JLabel();
        labelpetugas = new javax.swing.JLabel();
        inipanelnya = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelside1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        labelpinjam = new javax.swing.JLabel();
        labelkembali = new javax.swing.JLabel();
        panelside2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        panelside3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        labelkembali1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        paneljudul.setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Sekolah Menengah Kejuruan");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("TI Pembangunan Cimahi");

        jLabel6.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("\" SMK Bisa, SMK Bisa, Luar Biasa\"");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tip.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6))
                            .addComponent(jLabel5))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lblclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close Window_20px_6.png"))); // NOI18N
        lblclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcloseMouseClicked(evt);
            }
        });

        lblmaxim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Maximize Window_20px.png"))); // NOI18N
        lblmaxim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmaximMouseClicked(evt);
            }
        });

        lblminim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Minimize Window_20px_1.png"))); // NOI18N
        lblminim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimMouseClicked(evt);
            }
        });

        labelkod.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        labelkod.setForeground(new java.awt.Color(255, 255, 255));
        labelkod.setText("Kode");

        javax.swing.GroupLayout paneljudulLayout = new javax.swing.GroupLayout(paneljudul);
        paneljudul.setLayout(paneljudulLayout);
        paneljudulLayout.setHorizontalGroup(
            paneljudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneljudulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblminim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmaxim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblclose)
                .addGap(2, 2, 2))
            .addGroup(paneljudulLayout.createSequentialGroup()
                .addGroup(paneljudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneljudulLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paneljudulLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelkod)))
                .addGap(108, 108, 108)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(100, 100, 100))
        );
        paneljudulLayout.setVerticalGroup(
            paneljudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneljudulLayout.createSequentialGroup()
                .addComponent(lblminim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneljudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneljudulLayout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneljudulLayout.createSequentialGroup()
                        .addGroup(paneljudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(paneljudulLayout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelkod))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(paneljudulLayout.createSequentialGroup()
                .addGroup(paneljudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblclose)
                    .addComponent(lblmaxim))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelmenu.setBackground(new java.awt.Color(0, 255, 255));

        labeluser.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        labeluser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Enter_25px_1.png"))); // NOI18N
        labeluser.setText("Selamat Datang User");

        labelhak.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        labelhak.setForeground(new java.awt.Color(0, 102, 102));
        labelhak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_25px_2.png"))); // NOI18N
        labelhak.setText("User");

        javax.swing.GroupLayout panelmenuLayout = new javax.swing.GroupLayout(panelmenu);
        panelmenu.setLayout(panelmenuLayout);
        panelmenuLayout.setHorizontalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labeluser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelhak)
                .addGap(25, 25, 25))
        );
        panelmenuLayout.setVerticalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelhak)
                    .addComponent(labeluser))
                .addGap(5, 5, 5))
        );

        panelkonten.setBackground(new java.awt.Color(204, 255, 255));

        panelside.setBackground(new java.awt.Color(204, 255, 255));
        panelside.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Menu_15px.png"))); // NOI18N
        jLabel8.setText("Master");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        labelbuku.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelbuku.setForeground(new java.awt.Color(0, 102, 102));
        labelbuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Books_20px_3.png"))); // NOI18N
        labelbuku.setText("Data Buku");
        labelbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelbukuMouseClicked(evt);
            }
        });

        labelanggota.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelanggota.setForeground(new java.awt.Color(0, 102, 102));
        labelanggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Conference_20px_8.png"))); // NOI18N
        labelanggota.setText("Data Anggota");
        labelanggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelanggotaMouseClicked(evt);
            }
        });

        labelpetugas.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelpetugas.setForeground(new java.awt.Color(0, 102, 102));
        labelpetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User Groups_20px_7.png"))); // NOI18N
        labelpetugas.setText("Data Petugas");
        labelpetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelpetugasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelsideLayout = new javax.swing.GroupLayout(panelside);
        panelside.setLayout(panelsideLayout);
        panelsideLayout.setHorizontalGroup(
            panelsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelsideLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelbuku)
                    .addComponent(labelpetugas)
                    .addComponent(labelanggota))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        panelsideLayout.setVerticalGroup(
            panelsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsideLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(labelbuku)
                .addGap(10, 10, 10)
                .addComponent(labelanggota)
                .addGap(10, 10, 10)
                .addComponent(labelpetugas)
                .addGap(10, 10, 10))
        );

        inipanelnya.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout inipanelnyaLayout = new javax.swing.GroupLayout(inipanelnya);
        inipanelnya.setLayout(inipanelnyaLayout);
        inipanelnyaLayout.setHorizontalGroup(
            inipanelnyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inipanelnyaLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inipanelnyaLayout.setVerticalGroup(
            inipanelnyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inipanelnyaLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelside1.setBackground(new java.awt.Color(204, 255, 255));
        panelside1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Menu_15px.png"))); // NOI18N
        jLabel10.setText("Transaksi");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelpinjam.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelpinjam.setForeground(new java.awt.Color(0, 102, 102));
        labelpinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Borrow Book_20px_4.png"))); // NOI18N
        labelpinjam.setText("Peminjaman");
        labelpinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelpinjamMouseClicked(evt);
            }
        });

        labelkembali.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelkembali.setForeground(new java.awt.Color(0, 102, 102));
        labelkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Return_20px.png"))); // NOI18N
        labelkembali.setText("Pengembalian");
        labelkembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelkembaliMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelside1Layout = new javax.swing.GroupLayout(panelside1);
        panelside1.setLayout(panelside1Layout);
        panelside1Layout.setHorizontalGroup(
            panelside1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelside1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelside1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelkembali)
                    .addComponent(labelpinjam))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        panelside1Layout.setVerticalGroup(
            panelside1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelside1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(labelpinjam)
                .addGap(10, 10, 10)
                .addComponent(labelkembali)
                .addGap(10, 10, 10))
        );

        panelside2.setBackground(new java.awt.Color(204, 255, 255));
        panelside2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Menu_15px.png"))); // NOI18N
        jLabel15.setText("System");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 102));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit_20px.png"))); // NOI18N
        jLabel20.setText("Logout");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelside2Layout = new javax.swing.GroupLayout(panelside2);
        panelside2.setLayout(panelside2Layout);
        panelside2Layout.setHorizontalGroup(
            panelside2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelside2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel20)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        panelside2Layout.setVerticalGroup(
            panelside2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelside2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel20)
                .addGap(10, 10, 10))
        );

        panelside3.setBackground(new java.awt.Color(204, 255, 255));
        panelside3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Menu_15px.png"))); // NOI18N
        jLabel11.setText("Laporan");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelkembali1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        labelkembali1.setForeground(new java.awt.Color(0, 102, 102));
        labelkembali1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Return_20px.png"))); // NOI18N
        labelkembali1.setText("Data Perpustakaan");
        labelkembali1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelkembali1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelside3Layout = new javax.swing.GroupLayout(panelside3);
        panelside3.setLayout(panelside3Layout);
        panelside3Layout.setHorizontalGroup(
            panelside3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelside3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelkembali1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelside3Layout.setVerticalGroup(
            panelside3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelside3Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(labelkembali1)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelkontenLayout = new javax.swing.GroupLayout(panelkonten);
        panelkonten.setLayout(panelkontenLayout);
        panelkontenLayout.setHorizontalGroup(
            panelkontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelkontenLayout.createSequentialGroup()
                .addGroup(panelkontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelkontenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelside2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(panelkontenLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelkontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelside1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelside3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)))
                .addComponent(inipanelnya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelkontenLayout.setVerticalGroup(
            panelkontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelkontenLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelkontenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inipanelnya, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelkontenLayout.createSequentialGroup()
                        .addComponent(panelside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(panelside1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(panelside3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelside2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setForeground(new java.awt.Color(0, 51, 51));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Copyright_15px_4.png"))); // NOI18N
        jLabel7.setText("SMK TIP Cimahi");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(177, 177, 177)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(504, 504, 504))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneljudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelkonten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(paneljudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelkonten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        int jawab = JOptionPane.showOptionDialog(this, "Ingin Keluar?", "Keluar"
                + "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (jawab == JOptionPane.YES_OPTION) {
//            JOptionPane.showMessageDialog(this, "Program akan keluar");
            kf.masuk.setVisible(true);
            this.dispose();
        } else {
        }


    }//GEN-LAST:event_jLabel20MouseClicked

    private void labelanggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelanggotaMouseClicked
//        JOptionPane.showMessageDialog(this, "Anda telah mengakses data anggota. ");
        buatf.buatframe(inipanelnya, kf.siswa);
        td.tampildataanggota(kf.siswa.table);
           }//GEN-LAST:event_labelanggotaMouseClicked

    private void labelpetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelpetugasMouseClicked
//        JOptionPane.showMessageDialog(this, "Anda telah mengakses data petugas. ");
        buatf.buatframe(inipanelnya, kf.ptg);
        td.tampildatapetugas(kf.ptg.table);
        auto.kodepetugas(kf.ptg.txtid);
    }//GEN-LAST:event_labelpetugasMouseClicked

    private void labelbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbukuMouseClicked
//        JOptionPane.showMessageDialog(this, "Anda telah mengakses data buku. ");
       buatf.buatframe(inipanelnya, kf.buku);
       td.tampildatabuku(kf.buku.table);
       auto.kodebuku(kf.buku.txtid);
    }//GEN-LAST:event_labelbukuMouseClicked

    private void labelpinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelpinjamMouseClicked
//        JOptionPane.showMessageDialog(this, "Anda telah mengakses data pinjam. ");
       buatf.buatframe(inipanelnya, kf.pinjam);
//        td.tampildatabuku(kf.pinjam.tablebuku);
//        td.tampildataanggota(kf.pinjam.tablesiswa);
//        kelas.tgl.sekarang(kf.pinjam.tglpinjam);
//        td.tampildatapinjam(kf.pinjam.tabletransaksi);
        auto.kodepinjam(kf.pinjam.txtnopinjam);

    }//GEN-LAST:event_labelpinjamMouseClicked

    private void labelkembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelkembaliMouseClicked
//       JOptionPane.showMessageDialog(this, "Anda telah mengakses data pengembalian. ");
        buatf.buatframe(inipanelnya, kf.kembali);
//        kelas.td.tampildatapinjam(kf.kembali.tablepinjam);
//        kelas.tgl.sekarang(kf.kembali.tglkembali);
        auto.kodekembali(kf.kembali.txtkembali);
    }//GEN-LAST:event_labelkembaliMouseClicked

    private void labelkembali1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelkembali1MouseClicked
        buatf.buatframe(inipanelnya, kf.lpt);
        td.tampildatapetugas(kf.lpt.tablepetugas);
        td.tampildataanggota(kf.lpt.tablesiswa);
        td.tampildatakembali(kf.lpt.tabelPengembalian); 
        td.tampildatapinjam(kf.lpt.tablepinjam);
        td.tampildatabuku(kf.lpt.tablebuku);
//        kelas.td.tampildatapetugas(kf.lpt.tablepetugas);
    }//GEN-LAST:event_labelkembali1MouseClicked

    private void lblcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcloseMouseClicked
        int jawab = JOptionPane.showOptionDialog(this, "Ingin Keluar?", "Keluar"
                + "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (jawab == JOptionPane.YES_OPTION) {
            System.exit(0);
            this.dispose();
        } else {
        }
    }//GEN-LAST:event_lblcloseMouseClicked

    private void lblminimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_lblminimMouseClicked

    private void lblmaximMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmaximMouseClicked
        this.setExtendedState(this.MAXIMIZED_BOTH);

    }//GEN-LAST:event_lblmaximMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel inipanelnya;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private final javax.swing.JLabel labelanggota = new javax.swing.JLabel();
    private javax.swing.JLabel labelbuku;
    public static javax.swing.JLabel labelhak;
    private javax.swing.JLabel labelkembali;
    private javax.swing.JLabel labelkembali1;
    public static javax.swing.JLabel labelkod;
    public static javax.swing.JLabel labelpetugas;
    private javax.swing.JLabel labelpinjam;
    public static javax.swing.JLabel labeluser;
    private javax.swing.JLabel lblclose;
    private javax.swing.JLabel lblmaxim;
    private javax.swing.JLabel lblminim;
    private javax.swing.JPanel paneljudul;
    private javax.swing.JPanel panelkonten;
    private javax.swing.JPanel panelmenu;
    private javax.swing.JPanel panelside;
    private javax.swing.JPanel panelside1;
    private javax.swing.JPanel panelside2;
    public static javax.swing.JPanel panelside3;
    // End of variables declaration//GEN-END:variables
}
