/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author suryani lestari 14
 */
public class pinjam extends javax.swing.JDialog {

    /**
     * Creates new form pinjam
     */
    public pinjam(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        paneljudul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblclose = new javax.swing.JLabel();
        txtcapin = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablepinjam = new javax.swing.JTable();
        jLabel43 = new javax.swing.JLabel();
        cmbkat = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        paneljudul.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Menu_15px_1.png"))); // NOI18N
        jLabel1.setText("Data Peminjaman");

        lblclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close Window_20px_6.png"))); // NOI18N
        lblclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneljudulLayout = new javax.swing.GroupLayout(paneljudul);
        paneljudul.setLayout(paneljudulLayout);
        paneljudulLayout.setHorizontalGroup(
            paneljudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneljudulLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblclose))
        );
        paneljudulLayout.setVerticalGroup(
            paneljudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneljudulLayout.createSequentialGroup()
                .addGroup(paneljudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneljudulLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))
                    .addComponent(lblclose))
                .addContainerGap())
        );

        txtcapin.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtcapin.setForeground(new java.awt.Color(0, 102, 102));
        txtcapin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcapinKeyReleased(evt);
            }
        });

        tablepinjam.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tablepinjam.setForeground(new java.awt.Color(0, 102, 102));
        tablepinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Peminjaman", "Tanggal Pinjam", "NIS", "Nama Siswa", "ID Buku", "Judul", "Jumlah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablepinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepinjamMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tablepinjam);

        jLabel43.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 102, 102));
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search_20px.png"))); // NOI18N
        jLabel43.setText("Cari Berdasarkan");

        cmbkat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbkat.setForeground(new java.awt.Color(0, 102, 102));
        cmbkat.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cmbkatPopupMenuWillBecomeVisible(evt);
            }
        });
        cmbkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneljudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 683, Short.MAX_VALUE)
                        .addComponent(jLabel43)
                        .addGap(0, 0, 0)
                        .addComponent(cmbkat, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcapin, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(paneljudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbkat)
                        .addComponent(jLabel43))
                    .addComponent(txtcapin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcloseMouseClicked

        this.dispose();

    }//GEN-LAST:event_lblcloseMouseClicked

    private void txtcapinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcapinKeyReleased
        
        try {
            DefaultTableModel tm = (DefaultTableModel) tablepinjam.getModel();
            tm.setRowCount(0);
            int cariindex = cmbkat.getSelectedIndex();
            if (cariindex == 0) {
                koneksi.bahasasql = "SELECT a.*,b.* FROM transaksi_peminjaman a, detail_transaksi_peminjaman b WHERE a.no_pinjam LIKE '%" + txtcapin.getText() + "%'";
            } else if (cariindex == 1) {
                koneksi.bahasasql = "SELECT a.*,b.* FROM transaksi_peminjaman a, detail_transaksi_peminjaman b WHERE a.nis LIKE '%" + txtcapin.getText() + "%'";
            }else if (cariindex == 2) {
                koneksi.bahasasql = "SELECT a.*,b.* FROM transaksi_peminjaman a, detail_transaksi_peminjaman b WHERE a.nama_siswa LIKE '%" + txtcapin.getText() + "%'";
            }else if (cariindex == 3) {
                koneksi.bahasasql = "SELECT a.*,b.* FROM transaksi_peminjaman a, detail_transaksi_peminjaman b WHERE a.id_buku LIKE '%" + txtcapin.getText() + "%'";
            }else {
                koneksi.bahasasql = "SELECT a.*,b.* FROM transaksi_peminjaman a, detail_transaksi_peminjaman b WHERE a.judul LIKE '%" + txtcapin.getText() + "%'";
            }

            koneksi.ambildata();
            while (koneksi.hasilset.next()) {
                String npinjam ,nis, idp,kb,nama,namapet,judul;
                int jumlah;
                Date tglp, tglk;
                npinjam = koneksi.hasilset.getString("no_pinjam");
                tglp = koneksi.hasilset.getDate("tgl_pinjam");
                tglk = koneksi.hasilset.getDate("tgl_kembali");
                nis = koneksi.hasilset.getString("nis");
                nama = koneksi.hasilset.getString("nama_siswa");
                idp = koneksi.hasilset.getString("id_petugas");
                namapet = koneksi.hasilset.getString("nama_petugas");
                kb = koneksi.hasilset.getString("id_buku");
                judul = koneksi.hasilset.getString("judul");
                jumlah = koneksi.hasilset.getInt("jumlah");
                tm.addRow(new Object[]{npinjam,tglp,tglk,nis,idp,kb,jumlah});
            }
        } catch (SQLException ex) {
            Logger.getLogger(pinjam.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_txtcapinKeyReleased

    private void tablepinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepinjamMouseClicked
        try {
            String pilihid = tablepinjam.getValueAt(tablepinjam.getSelectedRow(), 0).toString();
            koneksi.bahasasql = "SELECT * FROM headpin INNER JOIN detailpem ON headpin.no_pinjam=detailpem.no_pinjam WHERE headpin.no_pinjam='" + pilihid + "'";
            koneksi.ambildata();
            while (koneksi.hasilset.next()) {
                String npinjam, nis, idp, kb, nama, namapet, judul;
                int jumlah;
                Date tglp, tglk;
                npinjam = koneksi.hasilset.getString("no_pinjam");
                tglp = koneksi.hasilset.getDate("tgl_pinjam");
                tglk = koneksi.hasilset.getDate("tgl_kembali");
                nis = koneksi.hasilset.getString("nis");
                nama = koneksi.hasilset.getString("nama_siswa");
                idp = koneksi.hasilset.getString("id_petugas");
                namapet = koneksi.hasilset.getString("nama_petugas");
                kb = koneksi.hasilset.getString("id_buku");
                judul = koneksi.hasilset.getString("judul");
                jumlah = koneksi.hasilset.getInt("jumlah");

                kf.kembali.txtpinjam.setText(npinjam);
                kf.kembali.tglpinjam.setDate(tglp);
                kf.kembali.tglharus.setDate(tglk);
                kf.kembali.txtnis.setText(nis);
                kf.kembali.txtbook.setText(kb);
                kf.kembali.spjumlah.setValue(jumlah);
                kf.kembali.txtnamasis.setText(nama);
                kf.kembali.txtjudul.setText(judul);
            }
        } catch (SQLException ex) {
            Logger.getLogger(pengembalian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tablepinjamMouseClicked

    private void cmbkatPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbkatPopupMenuWillBecomeVisible
         cmbkat.removeAllItems();
        cmbkat.addItem("No Pinjam");
        cmbkat.addItem("NIS");
        cmbkat.addItem("Nama Siswa");
        cmbkat.addItem("ID Buku");
        cmbkat.addItem("Judul");
    }//GEN-LAST:event_cmbkatPopupMenuWillBecomeVisible

    private void cmbkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                pinjam dialog = new pinjam(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbkat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblclose;
    private javax.swing.JPanel paneljudul;
    public static javax.swing.JTable tablepinjam;
    private javax.swing.JTextField txtcapin;
    // End of variables declaration//GEN-END:variables
}
